### ISSUE TITLE
Getting "Attempted to access an element as a type incompatible with the array" when doing new PowerBIClient

### ISSUE THREAD

**Issue by ThomasCronholm** [BennyM/PowerBI-CSharp#2]
Hi,

I am trying to create a new PowerBIClient as below:
`new PowerBIClient(new Uri(<someUri>), tokenCredentials)`
The token is a TokenCredentials with Bearer token.
But I only get a:
`System.Private.CoreLib: Attempted to access an element as a type incompatible with the array.`

I am using:
```
Microsoft.AspNet.WebApi.Client" Version="5.2.6"
Microsoft.Azure.KeyVault" Version="2.3.2" />
Microsoft.Azure.Services.AppAuthentication" Version="1.1.0-preview"
Microsoft.Azure.WebJobs" Version="3.0.0-beta5"
Microsoft.CSharp" Version="4.5.0" />
Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.14.2"
Newtonsoft.Json" Version="11.0.2"
PowerBI.Api" Version="1.0.9"
WindowsAzure.Storage" Version="8.6.0"
```

Please advise.

**Comment by BennyM** [comment]
Hi

Could you provide a full stack trace?

**Comment by BennyM** [comment]
Hi

I was looking into another reported issue and the TokenCredentials I use are located in the `Microsoft.Rest.ClientRuntime, Version=2.0.0.0` assembly.

**Comment by BennyM** [comment]
Closing this since there was no reply.
