### ISSUE TITLE
submitting http request returns html "Continue" page

### ISSUE THREAD

**Issue by pleepaul** [BennyM/PowerBI-CSharp#3]
Hi,

I have the exact issue of .net core not accepting UserPasswordCredential() and when I follow your code, I get a html response instead of json.  My username and password should be fine since it works when I use it in the AppOwnsData example.  Here is what I get when running the program (it actually fails then the program tries to parse the html as JSON) .  I get the same thing when I try to run this request in postman.

<html>
    <head>
        <title>Continue</title>
    </head>
    <body>
        <form method="POST" name="hiddenform" action="https://login.microsoftonline.com/common/oauth2/authorize">
            <input type="hidden" name="grant_type" value="password" />
            <input type="hidden" name="client_id" value="a216a5c9-12bd-45fa-bfd9-05865db9f2e1" />
            <input type="hidden" name="resource" value="https://analysis.windows.net/powerbi/api" />
            <input type="hidden" name="username" value="..." />
            <input type="hidden" name="password" value="..." />
            <input type="hidden" name="scope" value="openid" />
            <noscript>
                <p>Script is disabled. Click Submit to continue</p>
                <input type="submit" value="Submit" />
            </noscript>
        </form>
        <script language="javascript">window.setTimeout('document.forms[0].submit()', 0);</script>
    </body>
</html>

Thank you for your help!

Regards,
Paul

**Comment by BennyM** [comment]
Ok, thanks for the additional info. I'll look into it.

**Comment by BennyM** [comment]
Hi

I just tested with a blank console application and it just works. Try logging in with the account via a browser and see if you get any errors / warnings. 

I have not yet ported the most recent SDK to netstandard so perhaps there are some changes in it. Are you sure you are using "application/x-www-form-urlencoded" as per the sample code?

**Comment by pleepaul** [comment]
Hi Benny,

Thank you for your reply.  I just tested in a browser and it works fine although it uses MFA.  Would that be an issue in this case?  I didn't think about it since it worked fine when I entered it in the sample AppOwnsData app provided by Microsoft.  Would it be different using REST?

Thanks again,
Paul
________________________________

**Comment by BennyM** [comment]
That will be the issue, you need an “admin account” that does not require MFA. PowerBI does not know that it’s actually an application: https://docs.microsoft.com/en-us/power-bi/developer/get-azuread-access-token#access-token-for-non-power-bi-users-app-owns-data

Benny

**Comment by pleepaul** [comment]
Thank you Benny.  I tried on a test tenant without MFA and it does indeed work.  I will try to request an non-MFA account from my organization tenant to test.  Thank you for all your help!
________________________________

**Comment by marian-gheorghe** [comment]
Hi, 
I have tried your example (programatically) and as Postman request but it doesn't work for me 
![image](https://user-images.githubusercontent.com/39998360/46283171-f0671b00-c573-11e8-96d8-69f92c9cd764.png)

I need to mention that my account doesn't have MFA and I can login in browser without any issues
Any suggestion ?

**Comment by marian-gheorghe** [comment]
Just found the solution: use https://login.windows.net/common/oauth2/token/ as authority url

**Comment by mohibakhan** [comment]
vgg

**Comment by mohibakhan** [comment]
I'm also trying the same but I'm getting invaild_grant error, although the username and password I'm using are correct.

![git](https://user-images.githubusercontent.com/38834187/46748796-60675680-cc82-11e8-9292-88c4a67d9c09.PNG)
