### ISSUE TITLE
EffectiveIdentity does not support customData 

### ISSUE THREAD

**Issue by sealightPT** [BennyM/PowerBI-CSharp#4]
This property is missing on EffectiveIdentity:

[JsonProperty(PropertyName = "customData")]
public string CustomData { get; set; }

If we are calling the REST API, we can add custom data inside each identity, e.g.:

{
    "accessLevel": "View",
    "identities": [
        {
            "username": "EffectiveIdentity",
            "roles": [ "Role1", "Role2" ],
            "customData": "MyCustomData",
            "datasets": [ "fe0a1aeb-f6a4-4b27-a2d3-b5df3bb28bdc" ]
        }
    ]
}

https://docs.microsoft.com/en-us/power-bi/developer/embedded-row-level-security

**Comment by BennyM** [comment]
Thanks for reporting, is this in the latest official SDK?

**Comment by stevenwilliamsmis** [comment]
I am also looking for this as it will provide for row level security. I can also confirm that it is in the .net framework version of Microsoft's PowerBI nuget package version 2.0.14.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.v2.models.effectiveidentity?view=azure-dotnet

**Comment by stevenwilliamsmis** [comment]
It looks like your branch upgrade-to-latest-official-sdk has the change needed.

**Comment by BennyM** [comment]
I have pushed that branch to the master and an updated package is available. Please let me know if this solves the issue.

**Comment by BennyM** [comment]
Closing this since no more comments were made and a thumbs up was received. 😄
